from app.core.database import get_database, COLLECTIONS

COLLECTION_GRIEVANCES = COLLECTIONS["grievances"]
COLLECTION_USERS = COLLECTIONS["users"]
COLLECTION_STATUS_HISTORY = COLLECTIONS["status_history"]
COLLECTION_DEPARTMENTS = COLLECTIONS["departments"]
COLLECTION_NOTIFICATIONS = COLLECTIONS["notifications"]
